### ISSUE TITLE
Feedback for another grouo

### ISSUE THREAD

**Issue by sukh2929** [UBC-MDS/dsci532-group3-R#4]
The whole team to review. Arash to summarize into the issue for submission

**Comment by heidi-ye** [comment]
Hey Team, I took a look and here are my thoughts for group #4.

Things I liked:
- the formatting with the blocks and headings looks nice
- generally user friendly and easy to follow

Areas of improvement:
- label axis for the graphs (ie. Alcohol Consumption has no units so it's hard to interpret the graph)
- interactivity between graphs (ie. if I filter for Europe under continent, it would be nice for the bottom graph to also filter for Europe instead of showing everything)

**Comment by arashshams** [comment]
Hi all, my feedback as below:

**Thing I like:**
- Good job with archiving files within the repo.
- App sketch gives a thorough understanding of all the dashboard functionalities

**Areas of improvement:**
- Add interactivity to line charts for ease of reading the data
- The X-axis filter should be more informative with units
- The layout of heading for different features of the app (e.g. "Year-wise Trend" or "Country vs Continent vs Worldwide") can be improved.

**Comment by heidi-ye** [comment]
Arash to write up and submit issue to group 4. 

Additional comments:
- know that map is not working but reflected in documentation
-

**Comment by arashshams** [comment]
Done and posted: https://github.com/UBC-MDS/dsci_532_group_04_R/issues/13
